Disable stop on non-zero exit code

diff --git a/.github/workflows/upstream.yml b/.github/workflows/upstream.yml
--- a/.github/workflows/upstream.yml
+++ b/.github/workflows/upstream.yml
@@ -25,6 +25,8 @@ jobs:
 
       - name: "Copybara"
         run: |
+          # Allow us to capture the Docker exit code
+          set +e
           /usr/bin/docker run \
           -v "$(pwd)":/usr/src/app \
           -v /home/runner/.ssh/known_hosts:/root/.ssh/known_hosts \
@@ -33,6 +35,7 @@ jobs:
           ghcr.io/anipos/copybara-docker-image \
           --ignore-noop migrate /usr/src/app/.github/copy.bara.sky
           EXIT_CODE=$?
+          set -e
           if [ $EXIT_CODE -eq 4 ]; then
             exit 0
           fi
